version: '3.6'
services:
  mongodb:
    image: mongo:5.0.3
    container_name: mongo
    env_file: .env
    ports:
      - 27017:27017
    volumes:
      - ./mongo-volume:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/001_users.js:ro

volumes:
  mongo-volume:
